### ISSUE TITLE
Visualize analysis results with colors in Revit

### ISSUE THREAD

**Issue by anagpuyol** [tt-acm/DynamoSAP#22]
We could use the ImportInstance.ByGeometry when using Dynamo on Revit to visualize the surface version of the meshes created to visualize forces. Outputting a color for each of them according to their sign (+ or -) would make it really easy to see colors using Element.OverrideColorInView.

![image](https://cloud.githubusercontent.com/assets/2687679/5283689/1f5557be-7add-11e4-9bad-b4c8db03797b.png)

**Comment by bhowes-tt** [comment]
Closing this for now...  As discussed, our revit footprint will be relatively light on this project.  This is left over from the planning phase.
