### ISSUE TITLE
Update SAP Model Node !

### ISSUE THREAD

**Issue by eertugrul** [tt-acm/DynamoSAP#24]
inputs:
StructuralModel
FilePath _ Optional GrabOpen SAp Intance is path is not provided

output
modified Structural Model :+1: 

workflow should be:
// 1. LoopOver Structural Model Elements
with element.GUID query the element in SAP
if exists update the  properties of element  (dynamo> sap)
if not exists create new element (frm) and return Label and set the item

//2, delete elements
Loop over SAP Model elements if not found in StructuralModel, delete them from the SAP Model.

@howesben @anagpuyol 
I am thinking two options:
adding a Update.cs and and implementing all update nodes here!  see below
or 
we can add Bake.ToSap  a boolean input for create/update? if false is creating if true updating the model. But we need also an optional Filepath if the SAPmodel is not opened already! 

![image](https://cloud.githubusercontent.com/assets/4672688/5348994/1a55c9a4-7f03-11e4-99b1-e241efafaf95.png)

if update is true
update the open instance or exsitign one (use filepath)
if update false
create open new instance and save as given path if file path is set (path is optional) 

Bake.ToSAP also needs Units input that I will implement it soon. Please let me know your thoughts.

**Comment by bhowes-tt** [comment]
for the record - somewhat related to #30, which is still open.

**Comment by eertugrul** [comment]
I don't think we need any further changes on either Bake.toSAP and Collector to achieve #30 sap>dynamo>sap workflow.  Because when we read from sap we pass original labels of sap elements to dynamo elements. We just need nodes where pass the and output modified  object with same label.
 
for instance updateFrame node can be similar like fromLine node with additional input Frame!
