### ISSUE TITLE
IGraphicItem

### ISSUE THREAD

**Issue by anagpuyol** [tt-acm/DynamoSAP#28]
I found this class showcasing a sample to use the IGraphicItem interface.

While a point can be colored (tho not supported yet), I'm not sure how this applies to meshes (or surfaces), since the IRenderPackage has limited methods (points and lines). I'm posting this for possible future implementation...

https://github.com/DynamoDS/Dynamo/blob/fa132d423ad589ed1e79ea9555a1f80a9e473b95/src/Libraries/Samples/SampleLibraryZeroTouch/HelloDynamoZeroTouch.cs

**Comment by bhowes-tt** [comment]
related to #19 .  Closing this one.
