### ISSUE TITLE
Units in Dynamo

### ISSUE THREAD

**Issue by eertugrul** [tt-acm/DynamoSAP#29]
@bhowes-tt @anagpuyol 

I wanna discuss about dynamo units with u; 

For now I have just add Units Bake.ToSap node, so whatever the units selected from dropdown, the length is set as it is, for example length of this frame is drawn as 10 cm in sap Model. 

![image](https://cloud.githubusercontent.com/assets/4672688/5418922/e2b37b44-8214-11e4-8d26-882501fff74b.png)

I was able to read display units of Dynamo environment successfully. yayy ! But Ana and I thought to convert the input value from dynamounit(inunit) to sapunit (outunit) might be confusing to user. I have been looking for units issues at DynamoDS repo. Actually I got more confused. It seems the double output in dynamo is unit less. There is length nodes if length from double node returns converted values !

dynamo display lenght units is meter:
![image](https://cloud.githubusercontent.com/assets/4672688/5419198/783cf134-8217-11e4-9ad3-d9515ad9dd4b.png)

dynamo display length units is decimal inch
![image](https://cloud.githubusercontent.com/assets/4672688/5419241/e179be34-8217-11e4-91d5-d927f14cf617.png)

this means that Dynamo API is in meter !
So I just need to make conversion meter to what ever is SAP units selected right ? display units doesn't make any difference but it is confusing from a user point of view.

I am curious about your thoughts before I do some progress on this.

**Comment by bhowes-tt** [comment]
As per today's discussion, it sounds like @eertugrul is reading all doubles from dynamo in meters and converting to the active unit in SAP.  

@eertugrul - please close this if it's already resolved ... it sounded like it was today, just making sure.

**Comment by eertugrul** [comment]
@bhowes-tt yes it is true, double values in dynamo is in meter. 
I will check with Ian, I don't know what has really changed with latest dynamo.

**Comment by eertugrul** [comment]
for time being there is no changes. We should revisit units when Dynamo team make the changes.
