### ISSUE TITLE
outline of the nodes structures

### ISSUE THREAD

**Issue by eertugrul** [tt-acm/DynamoSAP#31]
@bhowes-tt @mnaugle-tt @anagpuyol 
I have started the organizational chart of nodes structure of Dynamo<>SAP link.  Please feel free to comment!

![image](https://cloud.githubusercontent.com/assets/4672688/5808340/43bb5ec2-9ffa-11e4-97f7-6719e9a818a3.png)

**Comment by bhowes-tt** [comment]
The organization looked good during our review meeting today - closing this.
