### ISSUE TITLE
Joint restraints when the input is a list

### ISSUE THREAD

**Issue by anagpuyol** [tt-acm/DynamoSAP#34]
![image](https://cloud.githubusercontent.com/assets/2687679/5859992/6e7aa936-a22c-11e4-81be-4b180a8f986a.png)

**Comment by bhowes-tt** [comment]
I couldn't quite understand the issue during our meeting today, but it sounded like it still needs to be resolved...  Assigning @anagpuyol

**Comment by eertugrul** [comment]
now it is working ! Beware the list should be Flatten list before collector! working now. 
![image](https://cloud.githubusercontent.com/assets/4672688/6086568/ece521d0-ae10-11e4-9741-137cef3ea316.png)

Thank you
