### ISSUE TITLE
Shells issue

### ISSUE THREAD

**Issue by anagpuyol** [tt-acm/DynamoSAP#35]
Labels not showing correctly.

![image](https://cloud.githubusercontent.com/assets/2687679/5866382/b0c90ef4-a25e-11e4-913a-af06d9159588.png)

**Comment by bhowes-tt** [comment]
@anagpuyol - can you elaborate please?  I don't understand the issue based only on the image...

**Comment by anagpuyol** [comment]
We found something to similar to what is happening with joints. When elements are collected into a list and Dynamo is run, the labels are modified unintentionally. In the case of the joints, the labels are empty; in the case of the shells, they drop the "dyn_" part of it. Very odd.

**Comment by bhowes-tt** [comment]
OK so it sounds like this is probably related to #34 too.

**Comment by eertugrul** [comment]
I fixed this one while #43 :hammer:
