### ISSUE TITLE
Read.SAPModel operation failed

### ISSUE THREAD

**Issue by mpdiker** [tt-acm/DynamoSAP#36]
Warning: Read.SAPModel operation failed. 
Retrieving the COM class factory for component with CLSID {05C24B9F-F327-47C2-B6EF-5660A8175ECB} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).

**Comment by mpdiker** [comment]
Same happens for SectionProp.Sections
Windows 7 Pro 64bit
Revit 2015 64bit
Dynamo 7.5
Sap2000 17.1.1 Build1099 32bit

Could it be because I have an 32 bit Sap2000?

**Comment by anagpuyol** [comment]
Hi mpdiker,

We have built the package for Dynamo 7.5 and Sap2000 version 16. You have version 17 of the latter so this is probably the source of your issue. We currently do not support v. 17. 

Please, let us know if you have any other questions. 

Thanks,

Ana

**Comment by Erichennn** [comment]
Same issue. I expect a new version compatible with v.17.
