### ISSUE TITLE
Typical release nodes

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/DynamoSAP#38]
Similar to fixities, we need to provide a set of typical release types.  We should ask Rob or @Reynolds534 for help defining these.  The types that made it into the scope are:
- Fixed
- Pinned
- BendingMoment

**Comment by anagpuyol** [comment]
Nodes created. However, I can't update frames and add them. Things fail again in https://github.com/tt-acm/DynamoSAP/blob/master/src/SAPConnection/StructureMapper.cs#L31

@eertugrul Please, check this update method when you have a minute. Thanks! :boat:

**Comment by eertugrul** [comment]
It worked fine on my end ! digging in more detail.
I noticed also the delete unconnected joints also not working anymore !

**Comment by eertugrul** [comment]
@anagpuyol Please test your release nodes again. Updating model should be working now. :+1:
