### ISSUE TITLE
Edit SAP model sample file

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/DynamoSAP#41]
We need to include a sample file that demonstrates how to edit an existing SAP model with Dynamo.  A couple of good use cases are 
- adding more groups to the model
- adding load cases to the model

This relates to #24 - we should also test geometrical updates, even though @eertugrul is skeptical.

**Comment by anagpuyol** [comment]
Reading a model in SAP, adding groups in Dynamo and baking works perfectly! @eertugrul @bhowes-tt :+1: :octopus:

**Comment by anagpuyol** [comment]
works for load cases and load patterns too. I made examples 3b and 3c for these.

**Comment by bhowes-tt** [comment]
@anagpuyol - relating to #24, did you happen to try any geometry?  It would be nice to know for sure that we need specific nodes for this.

**Comment by bhowes-tt** [comment]
wait --- looks like #30 is pretty similar to #24.... :lemon:   I'll comment on that one too.
