### ISSUE TITLE
Issue creating labels

### ISSUE THREAD

**Issue by anagpuyol** [tt-acm/DynamoSAP#43]
I think this is related to #34 

![image](https://cloud.githubusercontent.com/assets/2687679/6051241/6858444c-ac94-11e4-84b1-22e8af4e2a3c.png)

**Comment by anagpuyol** [comment]
Before calling Bake.ToSAP all the labels are correct. 

![image](https://cloud.githubusercontent.com/assets/2687679/6051309/f08d1202-ac94-11e4-96c6-d739dba00948.png)

**Comment by anagpuyol** [comment]
@eertugrul the StructureMapper fails here:

https://github.com/tt-acm/DynamoSAP/blob/master/src/SAPConnection/StructureMapper.cs#L31

Can you have a look at this? I have been running the sample file 1a

**Comment by eertugrul** [comment]
I believe this is a dynamo issue, I have repeated the same one when i merge the Joint with List.Create node. It is very weird indeed. Looking into it!

**Comment by anagpuyol** [comment]
Frames working

**Comment by eertugrul** [comment]
I am taking back my words: dynamo is working fine. It was my fault. Fixed...
