### ISSUE TITLE
I installed the DynamoSAP 0.1.17 and i have the dynamo 0.8.0.950

### ISSUE THREAD

**Issue by engsabbagh** [tt-acm/DynamoSAP#49]
I installed the DYNAMOSAP package but it is not appearing in UI

**Comment by anagpuyol** [comment]
Hi @engsabbagh we developed DynamoSAP for Dynamo 7.5. We hope to add support for version 8 in the next few days. We will keep you posted. Thanks.

**Comment by engsabbagh** [comment]
thx

**Comment by eertugrul** [comment]
hi @engsabbagh,
The new version of DynamoSAP package is compatible with Dynamo 1.1 and SAP 2000 v16.1.1 as of today
