### ISSUE TITLE
Problem with Bake.ToSAP or StructuralModel.Collector?

### ISSUE THREAD

**Issue by AndresGParra** [tt-acm/DynamoSAP#52]
Hi, i try to run an example file (Sample_1bSpacestructure) but i have this problem...
i use Dynamo 0.7.1 and SAP2000 v.16.1.1

Thanks
![captura de pantalla 2015-06-16 a las 12 21 31 a m](https://cloud.githubusercontent.com/assets/12906384/8176267/27c27fba-13be-11e5-90b2-62272be48b5c.png)

**Comment by anagpuyol** [comment]
Hi @AndresGParra we built DynamoSAP for Dynamo 7.5 and SAP 16.0. We'll be adding support for Dynamo 8.0 and SAP 16.1.1 in the next few days. We will keep you posted. Thanks

**Comment by eertugrul** [comment]
The new version of DynamoSAP package is compatible with Dynamo 1.1 and SAP 2000 v16.1.1.
Let me know if the problem persists
