### ISSUE TITLE
UI dropdowns do not show the saved state of the selected index

### ISSUE THREAD

**Issue by anagpuyol** [tt-acm/DynamoSAP#53]
When the dyn file is reopened, they show as if no selection has been made

**Comment by bhowes-tt** [comment]
@anagpuyol - use my latest EA4D code as a template.  It's not the prettiest, but it works:
https://github.com/tt-acm/EnergyAnalysisForDynamo/blob/master/src/EnergyAnalysisForDynamo_UI/EnergyAnalysisForDynamoDropdowns.cs

**Comment by anagpuyol** [comment]
I'm on it...! :airplane:

**Comment by anagpuyol** [comment]
this is now working!
