### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by thazell** [tt-acm/DynamoSAP#58]
![image](https://cloud.githubusercontent.com/assets/14113080/9664839/5030f1ba-523a-11e5-9d4f-a481f6646a28.png)

I'm having issues with the installation.  Is there somewhere I can find documentation?  I am using SAP2000 17 and Revit 2015 and Dynamo 0.8.1.1942

**Comment by anagpuyol** [comment]
Hi @thazell, we do not support SAP 17, we support SAP 16 in the current version.

**Comment by thazell** [comment]
@anagpuyol Thank you for the update, I'll have IT install SAP 16 on my computer and retry.
