### ISSUE TITLE
error reading dynamo sap nodes

### ISSUE THREAD

**Issue by ahmedgewaily** [tt-acm/DynamoSAP#59]
i'm trying to explore the dynamo sap example files but i have error reading the nodes for section definitions and other nodes 
![dynamosap](https://cloud.githubusercontent.com/assets/16732300/12372131/4d4fecdc-bc55-11e5-962a-e0f977b102a0.PNG)

**Comment by anagpuyol** [comment]
@ahmedgewaily thanks for posting this issue. We're going to work on upgrading our plugin so that it works with Dynamo 9.0.

Note for our group: the API changes are described here https://github.com/DynamoDS/Dynamo/wiki/API-Changes

**Comment by anagpuyol** [comment]
@ahmedgewaily we just added support for Dynamo 9.1. Please, get the latest version thru the package manager. Thanks!
