### ISSUE TITLE
DynamoSAP needs to be rebuilt against 1.x

### ISSUE THREAD

**Issue by tatlin** [tt-acm/DynamoSAP#60]
@howesben Current package on the package manager does not load in Dynamo 1.1. 

Can we have Max rebuild this? there are trivial changes between the APIs

Build error for library: C:\Users\mattj\AppData\Roaming\Dynamo\Dynamo Core\1.1\packages\DynamoSAP\bin\DynamoSAP.dll
Could not load type 'Autodesk.DesignScript.Runtime.RegisterForTraceAttribute' from assembly 'DynamoServices, Version=1.1.0.2025, Culture=neutral, PublicKeyToken=null'.
Failed to load library: C:\Users\mattj\AppData\Roaming\Dynamo\Dynamo Core\1.1\packages\DynamoSAP\bin\DynamoSAP.dll
Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\Users\mattj\AppData\Roaming\Dynamo\Dynamo Core\1.1\packages\DynamoSAP\bin\DynamoSAP.dll
Exception when attempting to load package DynamoSAP from C:\Users\mattj\AppData\Roaming\Dynamo\Dynamo Core\1.1\packages\DynamoSAP
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Saving C:\Users\mattj\AppData\Roaming\Dynamo\Dynamo Core\backup\backup.DYN ...
Backup file is saved: C:\Users\mattj\AppData\Roaming\Dynamo\Dynamo Core\backup\backup.DYN

**Comment by tatlin** [comment]
thanks @eertugrul is there any reason you repathed in the .csproj files instead of keeping $(DYNAMO_) pointing back to the cs.props? 

I was experimenting locally with something like this:

<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <OutputPath Condition="'$(OutputPath)' == ''">$(SolutionDir)..\bin\$(Platform)\$(Configuration)</OutputPath>
    <NunitPath Condition="'$(NunitPath)' == ''">$(SolutionDir)..\extern\NUnit</NunitPath>
    <REVIT_API Condition="'$(REVIT_API)' == ''">C:\Program Files\Autodesk\Revit 2017</REVIT_API>
    <DYNAMO_API Condition="'$(DYNAMO_API)' == ''">C:\Program Files\Dynamo\Dynamo Core 1.1\</DYNAMO_API>
    <SAP2000_API Condition="'$(SAP2000_API)' == ''">C:\Program Files (x86)\Computers and Structures\SAP2000 18 Eval\</SAP2000_API>
    <REVIT_VERSION>Revit_2017</REVIT_VERSION>
    <BaseIntermediateOutputPath>$(OutputPath)\int\</BaseIntermediateOutputPath>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <OutputPath Condition="'$(OutputPath)' == ''">$(SolutionDir)..\bin\$(Platform)\$(Configuration)</OutputPath>
    <NunitPath Condition="'$(NunitPath)' == ''">$(SolutionDir)..\extern\NUnit</NunitPath>
    <REVIT_API Condition="'$(REVIT_API)' == ''">C:\Program Files\Autodesk\Revit 2017</REVIT_API>
    <DYNAMO_API Condition="'$(DYNAMO_API)' == ''">C:\Program Files\Dynamo\Dynamo Core 1.1\</DYNAMO_API>
    <SAP2000_API Condition="'$(SAP2000_API)' == ''">C:\Program Files (x86)\Computers and Structures\SAP2000 18 Eval\</SAP2000_API>
    <REVIT_VERSION>Revit_2017</REVIT_VERSION>
    <BaseIntermediateOutputPath>$(OutputPath)\int\</BaseIntermediateOutputPath>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
</Project>

**Comment by eertugrul** [comment]
@tatlin right, I totally forgot about it.  I will fix it and update the package soon. This package works only SAP2000 v16

**Comment by tatlin** [comment]
is there a way to download v16 from their site?

**Comment by eertugrul** [comment]
himm, doesn't seem so. no,you can only request evaluation version 18. https://www.csiamerica.com/support/downloads

**Comment by tatlin** [comment]
ok, I am experimenting with changing the refs to v18, will see if this is a trivial change or exactly how much the SAP API has changed.  If it works I can publish a different branch if you are ok with that

**Comment by eertugrul** [comment]
sure thing, go for it. I know in fact that the initiation of an open instance has changed and SAP v18 also implements cOAPI now. lets try in the other branch I can give you a hand. You can find the .chm documentation here "C:\Program Files (x86)\Computers and Structures\SAP2000 18\CSI_OAPI_Documentation.chm"

**Comment by eertugrul** [comment]
@tatlin 
Matt, I will upgrade Dynamo SAP from the SAP2000 v16 to SAP2000 v18 ! I am very busy next two weeks but I will take care of it just after.  Hope this helps,

**Comment by eertugrul** [comment]
@tatlin just to let you know, I upgraded the package with SAP 2000 v18 in separate branch. I also published two packages that are compatible with dynamo 1.1 and 1.2 ! sample files are updated.
Let me know if anything else.

**Comment by tatlin** [comment]
Nice! Can't wait to try it

-matt

**Comment by williamsArcadis** [comment]
SAP 2000v20???

**Comment by eertugrul** [comment]
Thanks for your interest!  We haven’t been able to provide any support on our Dynamo projects for a while, but if anyone would like to submit a pull request that addresses this issue, we’d be very happy to release an update including the fix.
