### ISSUE TITLE
Upgrade SAP2000 v18

### ISSUE THREAD

**Issue by eertugrul** [tt-acm/DynamoSAP#61]

**Comment by bkim103** [comment]
Has this upgrade been completed?

Read.SAPModel operator yields the following warning:
Warning: Read.SAPModel operation failed. 
Retrieving the COM class factory for component with CLSID {05C24B9F-F327-47C2-B6EF-5660A8175ECB} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).

I have Dynamo 1.1 and SAP2000 18.

Thank you

**Comment by eertugrul** [comment]
@bkim103 
sorry to keep you waiting.
I have just upgraded the package to sap 18. you can find the packages compatible for version Dynamo 1.1 and 1.2 . The package version matches the Dynamo version so it is easy to find the compatible version. 
If you use Dynamo 1.1 get the DynamoPackage Version 1.1.0
![image](https://cloud.githubusercontent.com/assets/4672688/20075589/c41a3e62-a502-11e6-9f7e-b7bc9154f5d4.png)

I also updated the sample files, please let me know if anything else.

**Comment by bkim103** [comment]
@eertugrul Thank you for your response! I now have Dynamo 1.2 and DynamoSAP Package 1.2.10. When I try to run Sample 1a I get the following warning at the SectionProp.Sections node,

"Warning: SectionProp.Sections operation failed. Make sure a SAP Model is open!"

even though I have SAP open. I have also tried running Sample 2a and I get the same warning when trying to Read a SAP model. When I try the option of browsing the file and inputting the file path I get the following,

"Warning: Read.SAPModel operation failed. The system cannot find the file specified"

Please let me know what you think.

**Comment by xenofex22** [comment]
Dear Elçin Hocam,
Although my file path is correct  I get this error. When I run Read.SAPModel node.
"Warning: Read.SAPModel operation failed. 
The system cannot find the file specified"
By the way I use Dynamo 1.2.10 and SAP2000 v18.
Şimdiden teşekkürler ve başarılar!

**Comment by williamsArcadis** [comment]
any answer about this?
